apiVersion: v1
kind: Service
metadata:
  name: shopnow-frontend
  namespace: webapps
spec:
  selector:
    app: shopnow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
